server:
  port: 9191

spring:
  application:
    name: SERVICE-REGISTRY
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://api-gateway:8761/eureka
  instance:
      hostname: localhost